version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: mydata      
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build: . 
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db 
